### ISSUE TITLE
Module compiled

### ISSUE THREAD

**Issue by tejua** [Beaconstac/NearBee-iOS-SDK#11]
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.3 compiler:
Can you update it ?

**Comment by Souro7** [comment]
We will be releasing a newer version of the SDK built with the latest Swift version soon.

**Comment by Souro7** [comment]
We have released NearBee v3.0.0 with Swift 5.1.3 to Cocoapods. Thanks.
